name: ourESchool
description: A School Management Project
publish_to: "none"
version: 1.0.0-dev.1.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intro_views_flutter: ^2.8.0
  file_picker: ^1.4.3+2
  camera: ^0.5.7+4
  random_color: ^1.0.3
  intl: ^0.16.1
  division: ^0.8.7+2
  flutter_spinkit: ^4.1.2
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+2
  # flutter_plugin_pdf_viewer:
  #   git:
  #     url: git://github.com/tamhiupanTam/flutter_plugin_pdf_viewer
  permission_handler: ^4.3.0
  image: ^2.1.4
  image_picker: ^0.6.3+4
  photo_view: ^0.9.2
  path_provider: ^1.6.1
  flutter_plugin_pdf_viewer: ^1.0.7
  custom_radio_grouped_button: ^1.0.0


  # peek_and_pop: ^0.1.8
  # snap: ^1.0.0

  # State Management tools
  get_it: ^4.0.0
  provider: ^4.0.4

  # Icons
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.7.0

  # Firebase Dependencies
  firebase_auth: ^0.15.5+2
  firebase_core: ^0.4.4+2
  cloud_firestore: ^0.13.4
  firebase_storage: ^3.1.1
  firebase_analytics: ^5.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   rxdart: ^0.22.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Customicons
      fonts:
        - asset: assets/fonts/Customicons.ttf

    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Nunito-Italic.ttf
